name             'sprout-pyenv'
maintainer       'Konstantin Gredeskoul'
maintainer_email 'kigster@gmail.com'
license          'MIT'
description      'Installs/Configures pyenv'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.1'
supports         'mac_os_x'
depends          'sprout-base'
depends          'homebrew'
